name: My first Github Action
on: [push]
jobs:
  build-app:
    runs-on: ubuntu-latest
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install node modules
        run: yarn
      - name: Build the project
        run: yarn build
      - name: Deploy the project
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: yarn deploy
      - name: Setup done
        run: echo "Project build is done."
  test-app:
    runs-on: ubuntu-latest
    needs: build-app
    steps:
      - run: echo "Testing app..."
