name: My first Github Action
on: [push]
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install node modules
        run: yarn
      - name: Build the project
        run: yarn build
      - name: Set vercel env
        run: |
          cd build
          mkdir .vercel
          cd .vercel
          touch project.json
          echo '{"projectId":"wsE2z9OsjJBYscvHvO7NDIoZ","orgIdL":"prj_FazitJtwz5AbBBqzVyWgzgYWV9nf"}' > project.json
      - name: Deploy the project
        run: yarn deploy
      - name: Setup done
        run: echo "Project build is done."
