name: My first Github Action
on: [push]
jobs:
  build-app:
    runs-on: ubuntu-latest
    outputs:
      text: ${{ steps.finished.outputs.text }}
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install node modules
        run: yarn
      - name: Build the project
        run: yarn build
      - name: Deploy the project
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: yarn deploy
      - name: Setup done
        id: finished
        run: echo "::set-output name=text::hello-world-from-build-job"
  test-app:
    runs-on: ubuntu-latest
    needs: buildApp
    env:
      MY_JOB_OUTPUT: ${{ needs.buildApp.outputs.text }}
    steps:
      - run: echo $MY_JOB_OUTPUT
